// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using maverickApi.Data;

#nullable disable

namespace MaverickApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("maverickApi.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Material para motor",
                            Nombre = "Motor"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Material para transmision",
                            Nombre = "Transmision"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Material para suspension",
                            Nombre = "Suspension"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Material para Embrague",
                            Nombre = "Embrague"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Material de Hidraulica",
                            Nombre = "Hidraulica"
                        });
                });

            modelBuilder.Entity("maverickApi.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<string>("Rfc")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Telefono")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Rfc")
                        .IsUnique();

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Email = "hiro@hotmail.com",
                            FechaCreacion = new DateTime(2026, 4, 23, 20, 26, 43, 876, DateTimeKind.Local).AddTicks(1722),
                            Nombre = "Taller el giro",
                            Rfc = "24sa12e",
                            Telefono = "456734"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Email = "michael@gmail.com",
                            FechaCreacion = new DateTime(2026, 4, 23, 20, 26, 43, 876, DateTimeKind.Local).AddTicks(2063),
                            Nombre = "Michael Jackson",
                            Rfc = "345s32r",
                            Telefono = "56732245"
                        });
                });

            modelBuilder.Entity("maverickApi.Models.DetalleOrdenCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("OrdenCompraId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("OrdenCompraId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DetalleOrdenCompras");
                });

            modelBuilder.Entity("maverickApi.Models.DetalleVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VentaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("VentaId");

                    b.ToTable("DetalleVentas");
                });

            modelBuilder.Entity("maverickApi.Models.OrdenCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NumeroCompra")
                        .HasColumnType("longtext");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("OrdenCompras");
                });

            modelBuilder.Entity("maverickApi.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoBarras")
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Marca")
                        .HasColumnType("longtext");

                    b.Property<string>("Modelo")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("PrecioCompra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<string>("Sku")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Nombre");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CategoriaId = 1,
                            CodigoBarras = "1086543",
                            Descripcion = "Banda de motor de 10 pulgadas.",
                            FechaCreacion = new DateTime(2026, 4, 23, 20, 26, 43, 875, DateTimeKind.Local).AddTicks(8700),
                            Marca = "Autozone",
                            Modelo = "hrmg1224",
                            Nombre = "Banda 10 pulgadas",
                            PrecioCompra = 450m,
                            PrecioVenta = 905m,
                            ProveedorId = 1,
                            Sku = "bnd-1234",
                            Stock = 100
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            CategoriaId = 2,
                            CodigoBarras = "85728750",
                            Descripcion = "Soporte de transmision para Toyota Corolla 2000 - 2013 ",
                            FechaCreacion = new DateTime(2026, 4, 23, 20, 26, 43, 875, DateTimeKind.Local).AddTicks(9062),
                            Marca = "Autozone",
                            Modelo = "sop3456",
                            Nombre = "Soporte de transmision",
                            PrecioCompra = 250m,
                            PrecioVenta = 750m,
                            ProveedorId = 1,
                            Sku = "sdt-2333",
                            Stock = 100
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            CategoriaId = 3,
                            CodigoBarras = "254324378",
                            Descripcion = "Horquilla inferior trasera de fiat 100",
                            FechaCreacion = new DateTime(2026, 4, 23, 20, 26, 43, 875, DateTimeKind.Local).AddTicks(9066),
                            Marca = "Autozone",
                            Modelo = "horin1243254",
                            Nombre = "Horquilla inferior",
                            PrecioCompra = 344m,
                            PrecioVenta = 1200m,
                            ProveedorId = 1,
                            Sku = "hit-37698",
                            Stock = 100
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            CategoriaId = 5,
                            CodigoBarras = "38748543",
                            Descripcion = "Piston eleveador trasero",
                            FechaCreacion = new DateTime(2026, 4, 23, 20, 26, 43, 875, DateTimeKind.Local).AddTicks(9068),
                            Marca = "Diviro",
                            Modelo = "piset567",
                            Nombre = "Piston elevador trasero",
                            PrecioCompra = 12500m,
                            PrecioVenta = 23400m,
                            ProveedorId = 2,
                            Sku = "pet-32434",
                            Stock = 100
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            CategoriaId = 5,
                            CodigoBarras = "56765643",
                            Descripcion = "Linea del hidarulico",
                            FechaCreacion = new DateTime(2026, 4, 23, 20, 26, 43, 875, DateTimeKind.Local).AddTicks(9071),
                            Marca = "Diviro",
                            Modelo = "lihid213",
                            Nombre = "Linea de hidarulico",
                            PrecioCompra = 1255m,
                            PrecioVenta = 20300m,
                            ProveedorId = 2,
                            Sku = "lh-3435",
                            Stock = 100
                        },
                        new
                        {
                            Id = 6,
                            Activo = false,
                            CategoriaId = 5,
                            CodigoBarras = "325783",
                            Descripcion = "Rin de fibra de carbono de 14 pulgadas",
                            FechaCreacion = new DateTime(2026, 4, 23, 20, 26, 43, 875, DateTimeKind.Local).AddTicks(9073),
                            Marca = "Daguza",
                            Modelo = "Rifi69",
                            Nombre = "Rin 14 pulgadas",
                            PrecioCompra = 1230m,
                            PrecioVenta = 2500m,
                            ProveedorId = 3,
                            Sku = "",
                            Stock = 100
                        });
                });

            modelBuilder.Entity("maverickApi.Models.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Direccion")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<string>("Rfc")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Telefono")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Rfc")
                        .IsUnique();

                    b.ToTable("Proveedores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Direccion = "Col Miguel Hidalgo, Ciudad de Mexico.",
                            Email = "autozone@autozone.com",
                            FechaCreacion = new DateTime(2026, 4, 23, 20, 26, 43, 875, DateTimeKind.Local).AddTicks(3269),
                            Nombre = "Autozone SA de CV",
                            Rfc = "A12345678",
                            Telefono = "5506667812"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Direccion = "Blvd Benjamin Hill Culiacan Sin.",
                            Email = "diviro@hotmail.com",
                            FechaCreacion = new DateTime(2026, 4, 23, 20, 26, 43, 875, DateTimeKind.Local).AddTicks(3624),
                            Nombre = "Hidraulica Diviro SA de CV",
                            Rfc = "H1234567890",
                            Telefono = "6671020304"
                        },
                        new
                        {
                            Id = 3,
                            Activo = false,
                            Direccion = "Blvd Enrique Cabrera Culiacan Sin.",
                            Email = "daguza@hotmail.com",
                            FechaCreacion = new DateTime(2026, 4, 23, 20, 26, 43, 875, DateTimeKind.Local).AddTicks(3627),
                            Nombre = "Mantenimientos y Servicios Daguza SA de CV",
                            Rfc = "D12345",
                            Telefono = "6673121914"
                        });
                });

            modelBuilder.Entity("maverickApi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Admin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Apellidos")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Admin = true,
                            Apellidos = "Sistema",
                            Email = "admin@maverick.com",
                            FechaCreacion = new DateTime(2026, 4, 23, 20, 26, 43, 751, DateTimeKind.Local).AddTicks(693),
                            Nombre = "Admin",
                            PasswordHash = "$2a$11$I784CJCFbvsdRP3Jn5dTNe.zDztv0NMsVDsvZT9tvFyS.3Y4xeh82"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Admin = false,
                            Apellidos = "Sistema",
                            Email = "ventasr@maverick.com",
                            FechaCreacion = new DateTime(2026, 4, 23, 20, 26, 43, 874, DateTimeKind.Local).AddTicks(19),
                            Nombre = "Ventas",
                            PasswordHash = "$2a$11$74MdMGfC6II8joEGA6MVfO4Oz5pCNjKJUU4.AVZzeGnR5I.VVKYoe"
                        });
                });

            modelBuilder.Entity("maverickApi.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Iva")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("NumeroVenta")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SubtotalBruto")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("maverickApi.Models.DetalleOrdenCompra", b =>
                {
                    b.HasOne("maverickApi.Models.OrdenCompra", "OrdenCompra")
                        .WithMany("Detalles")
                        .HasForeignKey("OrdenCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("maverickApi.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrdenCompra");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("maverickApi.Models.DetalleVenta", b =>
                {
                    b.HasOne("maverickApi.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("maverickApi.Models.Venta", "Venta")
                        .WithMany("Detalles")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("maverickApi.Models.OrdenCompra", b =>
                {
                    b.HasOne("maverickApi.Models.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("maverickApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proveedor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("maverickApi.Models.Producto", b =>
                {
                    b.HasOne("maverickApi.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("maverickApi.Models.Proveedor", "Proveedor")
                        .WithMany("Productos")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Categoria");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("maverickApi.Models.Venta", b =>
                {
                    b.HasOne("maverickApi.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("maverickApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("maverickApi.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("maverickApi.Models.OrdenCompra", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("maverickApi.Models.Proveedor", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("maverickApi.Models.Venta", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
